### ISSUE TITLE
New loses path

### ISSUE THREAD

**Issue by jkt628** [adobe/cryptr#31]
## The problem

+ New does not preserve the path to New Secret.

## Environment

* Cryptr version (or git revision) that exhibits the issue: 0.2.0
* Desktop OS/version used to run Cryptr: openSUSE Leap 42.3
* Vault version: v0.9.1 (cgo)

## Details

i want to create a sibling for an existing value so i navigate the tree and click New; unfortunately, New Secret shows just _secret/_.

## Steps to Reproduce

1. launch _cryptr_.
1. login to a vault server.
1. use the tree navigator on the left to find an existing value.
1. verify Location shows the full path to the value.
1. click _+ New_ above the existing value.
1. notice Location shows _secret/_; it SHOULD show _secret/path/to/parent_.

**Comment by jcrowthe** [comment]
Fixed in latest master. (36c8bfec1a216b86d50321f467948e784d972f7a)
