### ISSUE TITLE
Cryprt doesn't display secrets tree

### ISSUE THREAD

**Issue by zabaweb** [adobe/cryptr#33]
## The problem

Cryprt doesn't display secrets tree

## Environment

* 2.0
* Windows 10 Enterprise x64
* Vault version: Vault v0.9.6

## Details

I suppose that I miss configured the policies.

## Steps to Reproduce
Starting the server:
```
vault server -dev -log-level=trace
vault secrets enable -path="develop" kv

vault policy write develop develop

vault auth enable ldap
vault write auth/ldap/config^
 url=XXX^
 userattr=userPrincipalName^
 insecure_tls=true^
 starttls=false^
 upndomain=XXX^
 binddn=""^
 userdn="XXX"

vault write auth/ldap/groups/developers policies=develop

vault write auth/ldap/users/<mylogin> groups=developers

vault write develop/login  value=developDbLogin
vault write develop/password  value=developDbPass 

```

develop policy file:
```
path "develop/*" {
  capabilities = ["read", "list", "update", "create", "delete"]
}

path "sys/policy/develop" {
    capabilities  = ["read", "list"]
}
```
When I login via LDAP I am able to search the secrets, there is nothing is secrets tree.
![2018-06-22_09h12_09](https://user-images.githubusercontent.com/25872450/41762866-7ddb16a2-75fc-11e8-8d1d-515c1dd71144.png)

**Comment by herisanu** [comment]
Bump?

**Comment by zabaweb** [comment]
Yes, still occurs

**Comment by jcrowthe** [comment]
@zabaweb and @herisanu Multiple secret backends support has been added in PR #35 to the master branch.
