### ISSUE TITLE
Poli

### ISSUE THREAD

**Issue by jrisch** [adobe/cryptr#38]
## The problem

The example policy in the readme doesn't work with the new v2 KV secret store in Vault. Cryptr just displays a load animation, and I have to quit Cryptr and start over again.

## Environment

* Cryptr version (or git revision) that exhibits the issue: 0.3.0-alpha
* Desktop OS/version used to run Cryptr: macOS 10.14.2
* Vault version: 1.0.1

## Details

The example policy in the readme doesn't work with the new v2 KV secret store in Vault. I have found this to work - I hope you can use it:

```
path "secret/data/*" {
  capabilities = ["create", "read", "update", "delete", "list"]
}

path "secret/metadata/*" {
  capabilities = ["list", "read", "delete", "update", "create"]
}

path "secret/delete/*" {
  capabilities = ["update"]
}

path "secret/undelete/*" {
  capabilities = ["update"]
}
```

As the Vault documentation about the delete/undelete part is a bit cryptic, I'm not sure if  it's correctly configured above. But to delete secrets in Cryptr, I had to define the delete path at least and the undelete path seems to work fine with the restore function in Cryptr.

**Comment by jcrowthe** [comment]
@jrisch Thanks for the comment. The policy found in the readme doc is only present to exemplify the Cryptr requirement to have Vault policies applied to a token be readable by that same token. (That is to say, if `sys/policy/demo` is applied to token A, then token A also needs read access to the `sys/policy/demo` path.) 

I'm glad you found the proper policy for access to the v2 backend, and I don't see further action needed here. Cheers!
