### ISSUE TITLE
Support for OIDC login

### ISSUE THREAD

**Issue by frealmyr** [adobe/cryptr#41]
## Feature request: OpenID Connect login option

Having tried out Cryptr with token login, i would love to see OIDC as an login option. As our users sign in with their Google Cloud account to access the vault.

![image](https://user-images.githubusercontent.com/29174850/66646517-a7d24b00-ec26-11e9-9e92-478f67855bc3.png)

**Comment by derBroBro** [comment]
I had a similar issue and tried to use an by OIDC created token instead. 
Sadly this is also not working as expected but I create a PR for this. #46 
Maybe this helps you as well.

**Comment by olahouze** [comment]
Hi

I download client crypts on last release (0.5.0) but I am same issue with oidc Google:
![image](https://user-images.githubusercontent.com/23030430/157238463-d07f05d1-e935-4140-9335-ae554e6446b0.png)

Could you check if it's always a bug or just a bad confguration on my localhost ?

Best regards

**Comment by jcrowthe** [comment]
Resolved by https://github.com/adobe/cryptr/pull/59. Closing old issue.
