### ISSUE TITLE
Add support for Vault namespaces

### ISSUE THREAD

**Issue by amuraru** [adobe/cryptr#51]
## The problem

In our Vault installation our team is using a Vault namespace. 
Can cryptr be configured to use this?
thanks

**Comment by jcrowthe** [comment]
Hey Adi. Yes, it is entirely possible, though I have not yet determined how much work it would be. With this FOSS project really only having one contributor (me) and with you being aware of my other priorities, I won't be able to give an ETA on when I'll be able to review this request.

**Comment by amuraru** [comment]
Thanks Jacob :) No worries, I'll try to see what that involves myself and maybe there will be two contributors here.
Nice tool by the way!

**Comment by Werevolk** [comment]
Hi all. Subscribed. Really interested in namespace support too.

**Comment by jcrowthe** [comment]
Namespace support has been added with https://github.com/adobe/cryptr/commit/cb6d34996aacb16d0c73c60c609e4fba1cb63638 which will be released soon as part of v0.6.0.
