### ISSUE TITLE
Created Secrets not displayed after logout

### ISSUE THREAD

**Issue by eliasbalasis** [adobe/cryptr#52]
## The problem

Secrets successfully created with Cryptr for Windows are lost at next login.

## Environment

Cryptr version (or git revision) that exhibits the issue:  0.4.0
Desktop OS/version used to run Cryptr: Windows 10
Vault version: 1.4.2

## Details

I was able to create secrets using Cryptp for Windows against a dev vault.
However, after logout I couldn't se the created secrets anymore, even though I have confirmed that the secrets are recorded in the vault using the Hashicorp UI

## Steps to Reproduce

Run Hashicorp Vault 1.4.2 dev server
Configure a KV secrets engine unser default path "kv/"
Create a new authentiation method of type "Username & Password"
Add a test user and "default" policy
Ad the following entry to "default" policy
path "kv/*" {
  capabilities = ["create", "read", "update", "delete", "list"]
}
Access the vault using Cryptr 0.4.0 for Windows
Login with created user
Create a few secrets.
Logout from Cryptr
Login again with Cryptr
The created secrets are missing.

Further observation revealed that even without logoff just clicking the refresh button makes the created secrets disappear.

**Comment by jcrowthe** [comment]
Please see the [Secret Discovery](https://github.com/adobe/cryptr#secret-discovery) section in the readme. Your reproduction steps do not include the requisite "read" permissions to the default policy. Without this permission explicitly granted, Cryptr has no programmatic way of discovering what secrets a token has access to.

**Comment by eliasbalasis** [comment]
Indeed, I should have noticed.

This now works.

Sincere thanks.
