### ISSUE TITLE
An error occurred while connecting to the provided URL

### ISSUE THREAD

**Issue by osminm** [adobe/cryptr#55]
## The problem

I was excited about the possibility of having a keepass-like-tool that would tie into Vault but was disappointed that no matter what I tried I can't even login to vault. The error I get on Windows or Mac is consistent: "An error occurred while connecting to the provided URL.". We do use namespaces in our environment but my testing has been against a root vault namespace.

## Environment

* Cryptr version 0.4.0 
* Desktop OS/version used to run Cryptr: Windows 10 (latest patch), Windows server 2019 (1809), OS X 10.15.7
* Vault version: Vault 1.4.1+prem.hsm

## Details

We have users that would prefer some sort of desktop client vs the web interface. They are not developers so the API/CLI just wouldn't be appropriate. 
![image](https://user-images.githubusercontent.com/33492177/109342818-6f8ed500-783a-11eb-9153-89df639f77da.png)

## Steps to Reproduce

Describe how to reproduce this issue. What did you click? What were you trying to do?
* Launch executable from either OS and the login window appears.
* Add a URL pointing to vault, tried with/without vault's default port
* The error appears immediately after trying to add a URL
* The error appears if I populate LDAP's user name/password and attempt to login
* The error appears when using Token and trying to populate URL & Token value as well.

**Comment by jcrowthe** [comment]
Would you try opening Cryptr in debug mode and look for console errors, or for what your Vault instance is responding with?

To enable this with released binaries, set the `CRYPTR_ENV=development` environment variable when launching the app. This is simple on Mac and Linux, though I see you're on Windows so will need to find how best to set it accordingly.

**Comment by osminm** [comment]
I hope this is useful..may try from a linux box also.
![image](https://user-images.githubusercontent.com/33492177/110262492-e2f2be00-7f81-11eb-83b3-222046ecff33.png)
![image](https://user-images.githubusercontent.com/33492177/110262513-f56cf780-7f81-11eb-98a3-185b7bdf2173.png)
![image](https://user-images.githubusercontent.com/33492177/110262528-01f15000-7f82-11eb-943f-d95faaf16e1a.png)
![image](https://user-images.githubusercontent.com/33492177/110262541-0f0e3f00-7f82-11eb-8691-88a5e0039dba.png)
![image](https://user-images.githubusercontent.com/33492177/110262567-1c2b2e00-7f82-11eb-887b-9a077d6787f4.png)

**Comment by osminm** [comment]
quick update, cryptr was able to connect to a replicated local testing vault after modifying the tls_cipher_suites crypto order in vault. Will test again when this change is promoted but I'm able to do basic tests now . Thx
![image](https://user-images.githubusercontent.com/33492177/110976132-894a1500-832e-11eb-92f1-38c26cfc4658.png)

**Comment by Siamert** [comment]
I too having the same problem,  can you please provide the tls_cipher_suite that worked?

**Comment by jcrowthe** [comment]
Closing old issue
