### ISSUE TITLE
set ldap mount /v1/auth/X/login where X can be ldap (or another mount point)

### ISSUE THREAD

**Issue by lgfausak** [adobe/cryptr#61]
## The problem

LDAP has a mount point in Hashcorp vault.  The default is ldap.  Perhaps the mount point could be a pulldown, or, could be specified as a string with a default of ldap.

## Environment

* Cryptr login screen for ldap

## Details

Login using ldap.  A screen shot it attached.  There is no place to put the ldap mount point.    The default ldap is used.

<img width="367" alt="Screen Shot 2022-01-11 at 11 58 42 AM" src="https://user-images.githubusercontent.com/2189483/149011119-9fdedf57-528e-4bac-9726-746104a0a289.png">

## Possible fixes.

The api posts to:

/v1/auth/**ldap**/login/

It would be helpful if the string **ldap** could be input from login screen allowing for other mount points.

## Notes.

The login-form.html could collect the ldapmount with a default value of 'ldap', then, when creating the login post:

`this.authURL = this.url + 'v1/auth/' + this.ldappath + '/login/' + this.username;`

**Comment by jcrowthe** [comment]
This feature has been added in https://github.com/adobe/cryptr/commit/058572efe80463209a62a8baadbee7d52ac5c2c9 which will be released in v0.6.0.
