### ISSUE TITLE
Error when using with Google OIDC

### ISSUE THREAD

**Issue by olahouze** [adobe/cryptr#62]
## The problem

When I want to use the Vault connection using google OIDC I get an error message

## Environment

* Cryptr version (or git revision) that exhibits the issue: 0.5.0
* Desktop OS/version used to run Cryptr: Ubuntu 20.0.4
* Vault version: 1.9.2

## Details

We have configured our Vault according to the manufacturer's recommendations ( [https://learn.hashicorp.com/tutorials/vault/oidc-auth?in=vault/auth-methods#enable-oidc-auth-method](https://learn.hashicorp.com/tutorials/vault/oidc-auth?in=vault/auth-methods#enable-oidc-auth-method) )

We have configured :

`allowed_redirect_uris="http://localhost:8250/oidc/callback"`

And we have the following error message when we use Cryptr:

![error](https://user-images.githubusercontent.com/23030430/162701518-cccb9f41-30cb-446f-8f18-d81507a9d315.png)

## Steps to Reproduce

Configure Vault with OIDC authentication using Google

**Comment by jcrowthe** [comment]
This is not a Vault or Cryptr issue. As part of the authentication flow, Google need to know which URI's are safe to redirect your request to. This setting needs to be made in your Google OIDC configuration. This doc may help: https://developers.google.com/identity/protocols/oauth2/openid-connect#setredirecturi
